# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "CYOA 5x12"
product_name = "CYOA 5x12"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "STHLM kb"
board = "nice!nano_v2"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_00"]
output_pins = ["P0_11"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 1
cols = 1
layers = 1
keymap = [
    [
        ["A"],
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
