# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "CYOA 5x12"
product_name = "CYOA 5x12"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "STHLM kb"
board = "nice!nano_v2"

[matrix]
input_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
output_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]

[layout]
rows = 8
cols = 8
layers = 1
keymap = [
    [
        ["Grave", "1", "2", "3", "4", "5", "6", "7"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U"],
        ["Escape", "A", "S", "D", "F", "G", "H", "J"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M"],
        ["8", "9", "0", "Backspace", "I", "O", "P", "Delete"],
        ["K", "L", "Semicolon", "Quote", "Comma", "Dot", "Slash", "Enter"],
        ["Bootloader", "LCtrl", "LAlt", "LGui", "_", "_", "Space", "_"],
        ["_", "_", "_", "_", "Left", "Down", "Up", "Right"]
    ]
]
#matrix_map = """
#(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (4,0) (4,1) (4,2) (4,3)
#(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (4,4) (4,5) (4,6) (4,7)
#(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (5,0) (5,1) (5,2) (5,3)
#(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (5,4) (5,5) (5,6) (5,7)
#(6,0) (6,1) (6,2) (6,3) (6,4)    (6,5)    (6,7) (7,4) (7,5) (7,6) (7,7)
#"""

#[[layer]]
#keys = """
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E   F    H  I  J  K  L
#"""

[ble]
enabled = true
