# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "CYOA 5x12"
product_name = "CYOA 5x12"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "STHLM kb"
chip = "rp2040"

[matrix]
input_pins = ["PIN_29", "PIN_28", "PIN_27", "PIN_26", "PIN_22", "PIN_20", "PIN_23", "PIN_21"]
output_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9"]

[layout]
rows = 8
cols = 8
layers = 1
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"]
    ]
]
#matrix_map = """
#(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (4,0) (4,1) (4,2) (4,3)
#(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (4,4) (4,5) (4,6) (4,7)
#(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (5,0) (5,1) (5,2) (5,3)
#(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (5,4) (5,5) (5,6) (5,7)
#(6,0) (6,1) (6,2) (6,3) (6,4)    (6,5)    (6,7) (7,4) (7,5) (7,6) (7,7)
#"""

#[[layer]]
#keys = """
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E  F  G  H  I  J  K  L
#A  B  C  D  E   F    H  I  J  K  L
#"""

[ble]
enabled = false
