# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "CYOA 5x12"
product_name = "CYOA 5x12"
vendor_id = 0x1209
product_id = 0x0001
manufacturer = "STHLM kb"
chip = "nrf52840"

[matrix]
input_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
output_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]

[layout]
rows = 8
cols = 8
layers = 1
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["A", "B", "C", "D", "E", "F", "G", "H"]
    ]
]

[ble]
enabled = true
